services:
  - type: web
    name: ai-pcra-service
    env: docker
    repo: https://github.com/EarlErrmeen2001/ai-pcra
    branch: main
    dockerfilePath: Backend/dockerfile
    buildCommand: ""
    startCommand: uvicorn server:app --host 0.0.0.0 --port 8000
    plan: free
    autoDeploy: true
    healthCheckPath: /
