services:
  - type: web
    name: ai-pcra
    plan: free
    runtime: docker
    region: oregon
    branch: main
    buildFilter:
      paths:
        - Backend/Dockerfile
        - render.yaml
    dockerfilePath: Backend/Dockerfile
    dockerContext: Backend
    autoDeploy: true
