# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy wheelhouse and install dependencies from it
COPY wheelhouse /app/wheelhouse
COPY requirements.txt /app/
RUN pip install --no-index --find-links=/app/wheelhouse -r requirements.txt

# Copy app code and static build
COPY server.py .
COPY app ./app

# Expose port and run the app
EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
